baseURL = "https://geo-analysis.netlify.app"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "ko-kr"
languageName = "Ko"
paginate = "6"
summaryLength = "10"
theme = "twentytwenty"
title = "공간정보 빅데이터 분석 플랫폼"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "문의하기"
weight = 2
[[menu.main]]
URL = "contact"
name = "문의하기"
weight = 3
[[menu.main]]
URL = "about"
name = "회사소개"
weight = 2
[[menu.main]]
URL = "/"
name = "홈"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Joongseob Kim"
description = "공간정보 격차를 줄입니다."
[params.banner]
heading = "기술을 통해 공간정보 격차를 줄입니다."
image = "images/main.jpg"
[params.blog]
enable = false
heading = "공간정보 빅데이터 분석 플랫폼 블로그입니다."
[params.call_to_action]
button_label = "문의"
button_url = "https://forms.gle/sbTNNVR3zgY2HRvE6"
content = "공간정보 활용 및 회사에 궁금하신 사항은 문의주세요."
enable = true
title = "문의하기"
[params.cookies]
enable = true
expire_days = 2
[params.footer]
address = "마포구 <br> 서울, 대한민국"
content = "기술을 통해 공간정보 격차를 줄입니다."
copyright = "Copyright &copy; 2021 [공간정보 빅데이터 분석 플랫폼](https://geo-analysis.netlify.app)"
hours = ""
title = "공간정보 빅데이터 분석 플랫폼"
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "#"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
