######################## default configuration ####################
baseURL = "geo-analysis.netlify.app"
title = "공간정보 빅데이터 분석 "
theme = "twentytwenty"
languageName = "Ko"
languageCode = "ko-kr"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45



############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "홈"
URL = "/"
weight = 1

[[menu.main]]
name = "회사소개"
URL = "about"
weight = 2

[[menu.main]]
name = "블로그"
URL = "blog"
weight = 3

[[menu.main]]
name = "문의하기"
URL = "contact"
weight = 4

[[menu.main]]
name = "Sample Page"
URL = "sample-page"
weight = 5

# only desktop menu
[[menu.desktop]]
name = "문의하기"
URL = "contact"
weight = 1


#################### default parameters ################################
[params]
# Meta data
description = "공간정보 디지털 격차를 줄입니다."
author = "Joongseob Kim"

# cookies
[params.cookies]
enable = true
expire_days = 2

# banner
[params.banner]
heading = "기술을 통해 공간정보 디지털 격차를 줄입니다."
image = "images/main.jpg"

# blog
[params.blog]
heading = "공간정보 빅데이터 분석 플랫폼 블로그입니다."

# call to action
[params.call_to_action]
enable = true
title = "문의하기"
content = "공간정보 활용에 궁금하신 사항은 문의주세요."
button_label = "문의"
button_url = "contact"

# gallery
[params.gallery]
enable = true

[[params.gallery.gallery_item ]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item ]]
image = "images/2020-square-1.png"


# footer
[params.footer]
title = "공간정보 빅데이터 분석 플랫폼"
content = "기술을 통해 공간정보 디지털 격차를 줄입니다."
address = "마포구 <br> 서울, 대한민국"
hours = ""
copyright = "Copyright &copy; 2021 [공간정보 빅데이터 분석 플랫폼](https://geo-analysis.netlify.app)"

############################# social site ########################
[params.social]
yelp = "#"
facebook = "#"
twitter = "#"
instagram = "#"
email = "#"
linkedin = "#"
